apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiAppName }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.apiAppName }}
spec:
  replicas: {{ .Values.apiAppReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.apiAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiAppName }}
    spec:
      volumes:
        - name: api-volume
          persistentVolumeClaim:
            claimName: api-pvc
      containers:
      - name: {{ .Values.apiAppName }}
        image: {{ .Values.apiImagePath }}:{{ .Values.apiImageVers }}
        volumeMounts:
          - mountPath: /usr/src/app/public
            name: api-volume
        ports:
        - containerPort: 3000
        env:
        - name: AUDIENCE_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: auth.audience
        - name: ISSUER_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: issuer.url
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongoName }}-connection-string
              key: mongo.url
        - name: WS_READ_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: ws.readTimeout
        - name: WS_SEND_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: ws.sendTimeout
        - name: RELEASE_VERSION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: release.version
        - name: DEPLOYMENT_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: deploy.environment
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: otel.url
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pvc
  namespace: ntt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.apiStorageClass }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiAppName }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.apiAppName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.apiAppName }}-allow-inbound-web-and-outbound-cert
  namespace: {{ .Values.namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.apiAppName }}
  egress:
  - toFQDNs:
    - matchName: {{ .Values.issuerDomain }}
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": grafana
    toPorts:
    - ports:
      - port: "{{ .Values.otelPort }}"
        protocol: TCP
  - toEndpoints:
    -matchLabels:
      "app": {{ .Values.mongoName }}
    toPorts:
    - ports:
      - port: "{{ .Values.mongoPort }}"
        protocol: TCP
  # add mongo egress
  ingress:
  - fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": {{ .Values.ingressNamespace }}
    toPorts:
    - ports:
      - port: "3000"
        protocol: TCP