{{- if .Values.lokiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiAppName }}-loki
  namespace: {{ .Values.namespace }}
stringData:
  # lokiUserId and lokiToken are injected by CI/CD through Helm values
  loki.userId: {{ .Values.lokiUserId | quote }}
  loki.token: {{ .Values.lokiToken | quote }}
immutable: false
{{- end }}
