apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongoName }}-connection-string
  namespace: {{ .Values.namespace }}
stringData:
  # mongoConnectionString will be set by the github action
  {{- if .Values.mongoConnectionString }}
  mongo.url: {{ .Values.mongoConnectionString }}
  {{- else }}
  mongo.url: mongodb://{{ .Values.mongoName }}-service:{{ .Values.mongoPort }}/{{ .Values.mongoDB }}
  {{- end }}
immutable: false