{{- if .Values.otelHeaders }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiAppName }}-otel
  namespace: {{ .Values.namespace }}
stringData:
  # otelHeaders is injected by CI/CD through Helm values
  otel.headers: {{ .Values.otelHeaders | quote }}
immutable: false
{{- end }}
