apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiAppName }}-s3-storage
  namespace: {{ .Values.namespace }}
stringData:
  # These are expected to be injected by CI/CD through Helm values
  storage.s3.endpoint: {{ .Values.storageS3Endpoint | quote }}
  storage.s3.bucket: {{ .Values.storageS3Bucket | quote }}
  storage.s3.accessKeyId: {{ .Values.storageS3AccessKeyId | quote }}
  storage.s3.secretAccessKey: {{ .Values.storageS3SecretAccessKey | quote }}
immutable: false
