apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.uiAppName }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.uiAppName }}
spec:
  replicas: {{ .Values.uiAppReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.uiAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.uiAppName }}
    spec:
      containers:
      - name: {{ .Values.uiAppName }}
        image: {{ .Values.uiImagePath }}:{{ .Values.uiImageVers }}
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: api.url
        - name: WS_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: ws.url
        - name: AUTH_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: auth.domain
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: auth.client
        - name: AUDIENCE_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: auth.audience
        - name: REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: auth.redirect
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.uiAppName }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.uiAppName }}
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.uiAppName }}-allow-inbound-web-only
  namespace: {{ .Values.namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.uiAppName }}
  egressDeny:
  - fromEntities:
    - "all"
  ingress:
  - fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": {{ .Values.ingressNamespace }}
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
