name: Deploy
on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - 'chart/**'
  #   branches:
  #     - main
jobs:
  deployment:
    strategy:
      fail-fast: true
      matrix:
        include:
          - environment: "Dev"
            helm-args: "-f chart/values-dev.yaml"
          - environment: "Prod"
    uses: ./.github/workflows/helm.yaml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
      extra-helm-args: ${{ matrix.helm-args }}
