name: Test Helm
run-name: Helm deploy to ${{ inputs.environment }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      extra-helm-args:
        required: false
        type: string
      branch:
        required: true
        type: string
    secrets:
      KUBE_CONFIG:
        required: true
      MONGODB_CONNECTION_STRING:
        required: false
      OTEL_CONFIG_STRING:
        required: true
jobs:
  helm:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
    steps:
      - name: Checkout ${{ inputs.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - id: get-release
        name: Get Release Version
        run: |
          RELEASE_VERSION=$(node -p "require('./package.json').version")
          echo "release_version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
      - id: preflight
        name: Preflight Checks
        run: |
          ls -l /usr/local/bin
          which helm
          which kubectl
      - id: kubeconfig
        name: Kubectl Config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          if ! [ -d ~/.kube ]; then mkdir ~/.kube; fi
          if ! [ -f ~/.kube/config ]; then touch ~/.kube/config; fi
          chmod go-rwx ~/.kube/config
          echo $KUBE_CONFIG | base64 -d > ~/.kube/config
      - id: clusterinfo
        name: Cluster Info
        run: |
          kubectl cluster-info
      - id: helm
        name: Helm Upgrade
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          DEPLOY_ENV: ${{ vars.DEPLOYMENT_ENVIRONMENT }}
          EXTRA_ARGS: ${{ inputs.extra-helm-args }}
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          OTEL_CONFIG_STRING: ${{ secrets.OTEL_CONFIG_STRING }}
          RELEASE_VERSION: ${{ steps.get-release.outputs.release_version }}
        run: |
          [[ ! -z "$MONGODB_CONNECTION_STRING" ]] && VALUE=`echo "$MONGODB_CONNECTION_STRING" | base64 -d` yq e -i ".mongoConnectionString=env(VALUE)" chart/values.yaml
          [[ ! -z "$OTEL_CONFIG_STRING" ]] && VALUE=`echo "$OTEL_CONFIG_STRING"` yq e -i ".otelConfig=env(VALUE)" chart/values.yaml
          grep mongoConnectionString < chart/values.yaml | wc -c
          helm upgrade --install -f chart/values.yaml $EXTRA_ARGS --set releaseVersion="$RELEASE_VERSION" --set deployEnv="$DEPLOY_ENV" ntt-infra chart