name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      extra-helm-args:
        required: false
        type: string
    secrets:
      KUBE_CONFIG:
        required: true
jobs:
  helm:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - id: preflight
        name: Preflight Checks
        run: |
          ls -l /usr/local/bin
          which helm
          which kubectl
      - id: kubeconfig
        name: Kubectl Config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          if ! [ -d ~/.kube ]; then mkdir ~/.kube; fi
          if ! [ -f ~/.kube/config ]; then touch ~/.kube/config; fi
          chmod go-rwx ~/.kube/config
          echo $KUBE_CONFIG | base64 -d > ~/.kube/config
      - id: clusterinfo
        name: Cluster Info
        run: |
          kubectl cluster-info
      - id: helm
        name: Helm Upgrade
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          EXTRA_ARGS: ${{ inputs.extra-helm-args }}
        run: |
          pwd
          which yq
          ls -l
          ls -l nttchart/values.yaml
          [[ ! -z "$MONGODB_CONNECTION_STRING" ]] && VALUE=`echo "$MONGODB_CONNECTION_STRING" | base64 -d` yq e -i ".mongoConnectionString=env(VALUE)" nttchart/values.yaml
          ls -l nttchart/values.yaml
          grep mongoConnectionString < nttchart/values.yaml | wc -c
          echo "$EXTRA_ARGS"
          echo helm upgrade --install -f nttchart/values.yaml $EXTRA_ARGS ntt-infra nttchart