name: Release
on:
  release:
    types: [published]
jobs:
  start-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      package_mui: ${{ steps.version-mono.outputs.package_mui }}
      package_api: ${{ steps.version-mono.outputs.package_api }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version-mono
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@github.com"
          git rev-list --tags --skip=1 --max-count=1
          PREV_TAG_HASH=$(git rev-list --tags --skip=1 --max-count=1)
          PREV_TAG=$(git describe --abbrev=0 --tags $PREV_TAG_HASH)
          for p in $(git diff --name-only "$GITHUB_REF_NAME" "$PREV_TAG" | grep "^packages\/*" | cut -d / -f2 | sort | uniq); do
            echo "package_$p=true"
            echo "package_$p=true" >> "$GITHUB_OUTPUT"
          done
  package-mui:
    needs: [start-release]
    if: needs.start-release.outputs.package_mui == 'true'
    uses: ./.github/workflows/docker.yaml
    permissions:
      contents: read
      packages: write
    with:
      package: mui
      registry: ghcr.io
  package-api:
    needs: [start-release]
    if: needs.start-release.outputs.package_api == 'true'
    uses: ./.github/workflows/docker.yaml
    permissions:
      contents: read
      packages: write
    with:
      package: api
      registry: ghcr.io