name: Release
on:
  release:
    types: [published]
jobs:
  start-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      package_mui: ${{ steps.version-mono.outputs.package_mui }}
      package_api: ${{ steps.version-mono.outputs.package_api }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version-mono
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@github.com"
          git rev-list --tags --skip=1 --max-count=1
          PREV_TAG_HASH=$(git rev-list --tags --skip=1 --max-count=1)
          PREV_TAG=$(git describe --abbrev=0 --tags $PREV_TAG_HASH)
          for p in $(git diff --name-only "$GITHUB_REF_NAME" "$PREV_TAG" | grep "^packages\/*" | cut -d / -f2 | sort | uniq); do
            echo "package_$p=true"
            echo "package_$p=true" >> "$GITHUB_OUTPUT"
          done
  package-mui:
    needs: [start-release]
    if: needs.start-release.outputs.package_mui == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build Package A
        env:
          ALL_PACKAGES: ${{ needs.start-release.outputs.packages}}
          PACKAGE_NAME: a
          DO_PACKAGE: ${{ needs.start-release.outputs.package_mui }}
        run: |
          echo "PACKAGES ARE \""$ALL_PACKAGES"\" \""$DO_PACKAGE"\""
          if ! [[ $DO_PACKAGE != true ]]; then
              echo "$PACKAGE_NAME unchanged - will not build"
              exit
          fi
          
          echo "BUILD IT"
  package-api:
    needs: [start-release]
    if: needs.start-release.outputs.package_api == 'true'
    uses: ./.github/workflows/docker.yaml
    permissions:
      contents: read
    with:
      package: api