name: Test MUI
on:
  push:
    paths:
      - 'packages/mui/**'
    branches-ignore:
      - main
jobs:
  test_mui:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4 
      - name: Check changed files
        run: |
          echo "hi"
          PREV_TAG_HASH=$(git rev-list --tags --skip=1 --max-count=1)
          PREV_TAG=$(git describe --abbrev=0 --tags $PREV_TAG_HASH)
          FIRST_COMMIT_AFTER_VERSION=$(git rev-list "$PREV_TAG...HEAD" | tail -n 2 | head -n 1)
          git diff --name-only "$GITHUB_REF_NAME" "$FIRST_COMMIT_AFTER_VERSION" | grep "^packages\/*"
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci -w packages/mui
      - name: Utils Unit Test
        run: npm run test:utils -w packages/mui
      - name: Test Build
        run: npm run build -w packages/mui

      