name: Test MUI
on:
  push:
    paths:
      - 'packages/mui/**'
    branches-ignore:
      - main
jobs:
  test_mui:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4 
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Node Modules
        run: npm ci
      - name: Lint Code
        run: npm -w packages/mui run lint
      - name: Utils Unit Test
        run: npm run test:utils -w packages/mui
      - name: Test Build
        env:
          DISABLE_ESLINT_PLUGIN: true
        run: npm run build -w packages/mui

      